<?php

namespace TAMAS\AstroBundle\Repository;

use TAMAS\AstroBundle\Entity\EditedText;
use TAMAS\AstroBundle\Entity\MeanMotion;

/**
 * EraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EraRepository extends \Doctrine\ORM\EntityRepository
{

       /**
     * getDependencies
     *
     * This method is part of the process of forcing deletion of an object.
     * We need to know what are the related fields that are linked to editedText (in order to unlink it before deleting it)
     *
     * @return array
     */
    public function getDependancies()
    {
        return [
            EditedText::class => [
                'era' => [
                    'unlinkMethod' => 'setEra',
                    'oneToMany' => true
                ]
            ]
        ];
    }

}
