<?php

namespace TAMAS\AstroBundle\Repository;

/**
 * PDFFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageFileRepository extends \Doctrine\ORM\EntityRepository {
    
}
