<?php

// Symfony\src\TAMAS\AstroBundle\Repository\LibraryRepository.php
namespace TAMAS\AstroBundle\Repository;


use Symfony\Component\Intl\Intl;
use TAMAS\AstroBundle\DISHASToolbox\Table\TAMASListTableTemplate;



/**
 * LibraryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LibraryRepository extends \Doctrine\ORM\EntityRepository
{

    /* _________________________________________________________ add data ______________________________________ */

    /**
     * prepareListForForm
     *
     * This method is used when the current entity is linked to a parent form.
     * It returns a custom DQL querybuilder (not the result!) which will be queried from the formType and findForAutofill.
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function prepareListForForm()
    {
        return $this->createQueryBuilder('l')->orderBy('l.city', 'ASC');
    }


    /**
     * findForAutofill
     *
     * This method is triggered in the parent entity form type by ajax. It returns the getLabel list of object of the entity class.
     *
     * @return array : each value of the array contains an id and a title which are used in the ajax request to populate the select choice of the form such as <selec><option = "id">title</option>.
     */
    public function findForAutofill()
    {
        $entities = $this->prepareListForForm()
            ->getQuery()
            ->getResult();
        $answers = array();
        foreach ($entities as $entity) {
            $answers[] = [
                "id" => $entity->getId(),
                "title" => (string) $entity
            ];
        }
        return $answers;
    }

    /* __________________________________________________ list data ___________________________________________________ */

    /**
     * getList
     *
     * This method is roughly equivalent to findAll(), but it lowers the number of queries to the database by selecting
     * only the field that we are interested in displaying.
     *
     * @return array (library Object)
     */
    public function getList()
    {
        $queryResult = $this->createQueryBuilder('l')
            ->leftJoin('l.createdBy', 'c')
            ->addSelect('c')
            ->getQuery()
            ->getResult();
        return $queryResult;
    }

    /**
     * getObjectList
     *
     * This function generates the specs for listing a given collection of editedTexts: both the list of data (pre-treated for the front library) and the spec of the table (adapted to the front library).
     *
     * @param array $libraries
     *            : collection of all the libraries
     * @return array : containing the list of fields and the list of data ;
     */
    public function getObjectList($libraries)
    {
        $fieldList = [
            new TAMASListTableTemplate('id', '#'),
            new TAMASListTableTemplate('libraryName', 'Name'),
            new TAMASListTableTemplate('city', 'City'),
            new TAMASListTableTemplate('libraryIdentifier', 'ISNI'),
            new TAMASListTableTemplate('created', 'Created', [] , 'adminInfo'),
            new TAMASListTableTemplate('updated', 'Updated', [], 'adminInfo'),
            new TAMASListTableTemplate('buttons', '', [], 'editDelete')
        ];
        
        $data = $libraries;
        if ($libraries === null) {
            $data = $this->getList();
        }
        $refinedData = [];
        foreach ($data as $d) {
            $created = '';
            $updated = '';
            $createdBy = [];
            $updatedBy = [];
            $libraryName = '';
            $city = '';
            $libraryIdentifier = '';
            if ($d->getLibraryName()) {
                $libraryName = $d->getLibraryName();
            }
            if ($d->getCity()) {
                $city = $d->getCity();
            }
            if ($d->getLibraryCountry()) {
                $city .= " (" . $d->getLibraryCountry() . ")";
            }
            if ($d->getLibraryIdentifier()) {
                $libraryIdentifier = $d->getLibraryIdentifier();
            }
            if ($d->getCreated()) {
                $created = $d->getCreated()->format('d/m/y');
            }
            if ($d->getUpdated()) {
                $updated = $d->getUpdated()->format('d/m/y');
            }
            if ($d->getCreatedBy()) {
                $createdBy = [
                    'id' => $d->getCreatedBy()->getId(),
                    'username' => $d->getCreatedBy()->getUserName()
                ];
            }
            if ($d->getUpdatedBy()) {
                $updatedBy = [
                    'id' => $d->getUpdatedBy()->getId(),
                    'username' => $d->getUpdatedBy()->getUsername()
                ];
            }
            $refinedData[] = [
                'libraryName' => $libraryName,
                'city' => $city,
                'libraryIdentifier' => $libraryIdentifier,
                'created' => $created,
                'updated' => $updated,
                'createdBy' => $createdBy,
                'updatedBy' => $updatedBy,
                'id' => $d->getId()
            ];
        }
        return [
            'fieldList' => $fieldList,
            'data' => $refinedData
        ];
    }

    /**
     * This function is temporary used for the ajax call of the list of entity.
     * To be improved in the merging of list logic //TODO
     *
     * @param {array} of $library objects
     * @return {array} of $library objects
     */
    public function getFormatedList($libraries = null)
    {
        if ($libraries) {
            return $libraries;
        }
        return [];
    }

    /**
     * getDependencies
     *
     * This method is part of the process of forcing deletion of an object.
     * We need to know what are the related fields that are linked to library (in order to unlink it before deleting it)
     *
     * @return array
     */
    public function getDependancies()
    {
        return [
            \TAMAS\AstroBundle\Entity\PrimarySource::class => [
                'library' => [
                    'unlinkMethod' => 'setLibrary',
                    'oneToMany' => true
                ]
            ]
        ];
    }

    public function getCountryName(\TAMAS\AstroBundle\Entity\Library $library)
    {
        if (! $library) {
            return null;
        }

        /*return Intl::getRegionBundle()->getCountryName($library->getLibraryCountry());*/
        return $library->getLibraryCountry();
    }
}
