<?php

namespace TAMAS\AstroBundle\Repository;

/**
 * NumberUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumberUnitRepository extends \Doctrine\ORM\EntityRepository
{
}
