<?php

namespace TAMAS\AstroBundle\Repository;

/**
 * ParameterTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParameterTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
