<?php

namespace TAMAS\AstroBundle\Repository;

/**
 * ParameterGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParameterGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
