<?php

namespace TAMAS\AstroBundle\Repository;

/**
 * ParameterFeatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParameterFeatureRepository extends \Doctrine\ORM\EntityRepository
{
}
