<?php

namespace TAMAS\AstroBundle\Repository;

/**
 * ParameterUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParameterUnitRepository extends \Doctrine\ORM\EntityRepository
{
}
