<?php

namespace TAMAS\AstroBundle\Repository;

/**
 * ParameterFormatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParameterFormatRepository extends \Doctrine\ORM\EntityRepository {

    /**
     * prepareListForForm
     *
     * This method is used when the current entity is linked to a parent form.
     * It returns a custom DQL query builder (not the result!) which will be queried
     * from the formType and findForAutofill.
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function prepareListForForm() {
        return $this->createQueryBuilder('p')
                    ->leftJoin('p.tableType', 't')
                    ->leftJoin('t.astronomicalObject', 'a')
                    ->orderBy('a.id, t.tableTypeName');
    }

}
