<?php

namespace TAMAS\AstroBundle\Repository;

/**
 * PDFFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PDFFileRepository extends \Doctrine\ORM\EntityRepository
{
    public function getGeneralDocumentation() {
        return $this->findBy(['entityDefinition' => null]);
    }
    public function getModelDocumentation() {
        return $this->findBy(['entityDefinition' => 24]);
    }
}
