<?php

namespace TAMAS\AstroBundle\Repository;

/**
 * PythonScriptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PythonScriptRepository extends \Doctrine\ORM\EntityRepository
{
}
