<?php

namespace TAMAS\AstroBundle\Repository;

/**
 * SubTimeUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubTimeUnitRepository extends \Doctrine\ORM\EntityRepository
{
}
