<?php

namespace TAMAS\AstroBundle\Repository;

/**
 * TypeOfNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeOfNumberRepository extends \Doctrine\ORM\EntityRepository
{
    function getNameToBase(){
       $bases = $this->findAll();
       $res = [];
       foreach ($bases as $base){
           $list = json_decode($base->getBaseJSON(), 1);
           $list['name'] = $base->getCodeName();
           if($base->getIntegerSeparatorJSON() != NULL) {
               $list['integerSeparators'] = json_decode($base->getIntegerSeparatorJSON(), 1);
           }
           $res[$list['name']] = $list;
       }
       return $res;
    }
}
