<?php

namespace TAMAS\AstroBundle\Repository;

/**
 * UserInterfaceTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserInterfaceTextRepository extends \Doctrine\ORM\EntityRepository
{
}
