# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_ALFA_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALFA_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

        # in_memory:
            # memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        # I might have to comment the dev lines with FOSUser
        #dev:
            #pattern: ^/(_(profiler|wdt)|css|images|js)/
            #security: false

        main:
            pattern: ^/
            logout: true
            anonymous: true
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            form_login: 
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: tamas_astro_adminHome
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            
            logout:
                path: fos_user_security_logout
                target: /platform

            remember_me: 
                secret: %secret%
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/adm/, role: ROLE_ADMIN }
        - { path: ^/super-adm/, role: ROLE_SUPER_ADMIN }
        - { path: ^/alfa/adm/, role: ROLE_ALFA_ADMIN}