<?php

namespace TAMAS\ALFABundle\Repository;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ALFAXMLFileRepository extends \Doctrine\ORM\EntityRepository
{
}
