<?php

namespace TAMAS\ALFABundle\Repository;

/**
 * PrimarySourceWorkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrimarySourceWorkRepository extends \Doctrine\ORM\EntityRepository
{
}
