<?php

namespace TAMAS\ALFABundle\Repository;

use TAMAS\ALFABundle\Entity\ALFALibrary;

/**
 * PrimarySourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrimarySourceRepository extends \Doctrine\ORM\EntityRepository
{

	public function getLabel($primaySource){//typer ici
		$shelfmark = $primaySource->getShelfmark();
		$library = '';
		$collection = $primaySource->getCollection();
		if($primaySource->getLibrary()){
            $library = $this->getEntityManager()->getRepository(ALFALibrary::class)->getLabel($primaySource->getLibrary());
		}
		if($collection !== ''){
			$collection .= " ";
		}

		return $library.$collection.$shelfmark;
		//penser à un return pour les early printed

	} 
}
